[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/olympus-api/*"
  to = "https://gcp.olympus.io/:splat"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*"}
